analyzer:
  errors:
    constant_identifier_names: ignore
    annotate_overrides: ignore
    use_build_context_synchronously: ignore
    non_constant_identifier_names: ignore
include: package:flutter_lints/flutter.yaml
linter:
  rules:
    
    



