name: qrmark
description: "A new Flutter project."


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  flutter_secure_storage: ^9.2.4
  pretty_qr_code: ^3.3.0
  mobile_scanner: ^6.0.10
  audioplayers: ^6.4.0
  flutter_local_notifications: ^19.0.0
  sound_library: ^1.0.0
  dio: ^5.8.0+1
  package_info_plus: ^8.3.0
  flutter_zustand: ^0.0.5
  lucide_icons_flutter: ^2.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
